
export enum UpgradeKey {
  PRIORITIZE_UNVISITED = 'PRIORITIZE_UNVISITED',
  AVOID_REVISIT_LAST_POSITION = 'AVOID_REVISIT_LAST_POSITION',
  AUTO_EXIT_MAZE = 'AUTO_EXIT_MAZE',
  PLAYER_MOVE_INDEPENDENTLY = 'ALLOW_PLAYER_TO_MOVE_INDEPENDENTLY',
  TELEPORT_BOT_BACK_TO_PLAYER = 'TELEPORT_BOT_BACK_TO_PLAYER',
  TELEPORT_PLAYER_BACK_TO_BOT = 'TELEPORT_BOT_BACK_TO_PLAYER',
  BOT_SPLIT_DIRECTION = 'BOT_SPLIT_DIRECTION',
  BOT_SPLIT_BOT_AUTO_MERGE = 'BOT_SPLIT_BOT_AUTO_MERGE',
  TILE_REVISIT_MULTIPLIER = 'TILE_REVISIT_MULTIPLIER',
  MAZE_COMPLETION_BONUS = 'MAZE_COMPLETION_BONUS',
  BOT_MOVEMENT_SPEED = 'BOT_MOVEMENT_SPEED',
  BOT_REMEMBER_DEADEND_TILES = 'BOT_REMEMBER_DEADEND_TILES',
  MAZE_SIZE_UPGRADE = 'MAZE_SIZE_UPGRADE',
  POINTS_PER_VISIT = 'POINTS_PER_VISIT',
  FRUIT_SPAWN = 'FRUIT_SPAWN',
  FRUIT_PICKUP_POINTS = 'FRUIT_PICKUP_POINTS',
}


export const PRIORITIZE_UNVISITED_UPGRADE_COST = 500;
export const AVOID_REVISIT_LAST_POSITION_UPGRADE_COST = 1000;
export const ALLOW_PLAYER_TO_MOVE_INDEPENDENTLY_UPGRADE_COST = 1500;

export const AUTO_EXIT_MAZE_UPGRADE_BASE_COST = 250;
export const AUTO_EXIT_MAZE_UPGRADE_BASE_COST_MULTIPLIER = 2;

export const TELEPORT_PLAYER_BACK_TO_BOT_UPGRADE_COST = 1000;
export const TELEPORT_BOT_BACK_TO_PLAYER_UPGRADE_COST = 1000;

export const SPLIT_DIRECTION_UPGRADE_BASE_COST = 1000;
export const SPLIT_DIRECTION_UPGRADE_BASE_MULTIPLIER = 5;

export const SPLIT_BOT_AUTO_MERGE_UPGRADE_COST = 50000;

export const TILE_REVISIT_MULTIPLIER = 0;

export const MAZE_COMPLETION_BONUS_BASE_MULTIPLIER = 0.1;
export const MAZE_COMPLETION_BONUS_UPGRADE_SIZE_MULTIPLIER = 1.1;

export const MAZE_COMPLETION_BONUS_UPGRADE_BASE_COST = 100;
export const MAZE_COMPLETION_BONUS_UPGRADE_BASE_COST_MULTIPLIER = 2;

export const BOT_MOVEMENT_UPGRADE_BASE_COST = 10;
export const BOT_MOVEMENT_UPGRADE_BASE_COST_MUTLIPLIER = 1.1;

export const BOT_REMEMBER_DEADEND_TILES_UPGRADE_BASE_COST = 1000;
export const BOT_REMEMBER_DEADEND_TILES_UPGRADE_BASE_COST_MULTIPLIER = 3;

export const MAZE_SIZE_UPGRADE_BASE_COST = 100;
export const MAZE_SIZE_UPGRADE_BASE_COST_MULTIPLIER = 4;

export const POINTS_PER_VISIT_UPGRADE_BASE_COST = 10;
export const POINTS_PER_VISIT_UPGRADE_BASE_COST_MULTIPLIER = 2;
export const POINTS_PER_VISIT_BASE_AMOUNT = 1;
export const POINTS_PER_VISIT_BASE_AMOUNT_MULTIPLIER = 1.1

export const FRUIT_SPAWN_UPGRADE_BASE_COST = 10;
export const FRUIT_SPAWN_UPGRADE_BASE_COST_MULTIPLIER = 2;
export const FRUIT_SPAWN_BASE_PROBABILITY = .01;

export const FRUIT_PICKUP_POINTS_UPGRADE_BASE_COST = 10;
export const FRUIT_PICKUP_POINTS_UPGRADE_BASE_COST_MULTIPLIER = 2;
export const FRUIT_PICKUP_POINTS_BASE_AMOUNT = 10;
export const FRUIT_PICKUP_POINTS_BASE_AMOUNT_MULTIPLIER = 1.2;
