
export enum MazeItemKey {
  FRUIT = "FRUIT",
  BRAIN = "BRAIN",
  MULTIPLIER = "MULTIPLIER",
  BLACK_HOLE = "BLACK_HOLE"
}


export const FRUIT_SPAWN_UPGRADE_FLAT_INCREASE_PROBABILITY = 0.00075;
export const FRUIT_SPAWN_BASE_PROBABILITY = 0.005;
export const FRUIT_PICKUP_POINTS_BASE_AMOUNT = 20;
export const FRUIT_PICKUP_POINTS_BASE_AMOUNT_MULTIPLIER = 1.2;

export const BRAIN_SPAWN_BASE_PROBABILITY = 0.001;
export const BRAIN_STARTING_TILE_DISTANCE = 20;

export const MULTIPLIER_ITEM_SPAWN_BASE_PROBABILITY = 0.001;
export const MULTIPLIER_ITEM_BASE_MULTIPLIER = 2;

export const BLACK_HOLE_ITEM_SPAWN_BASE_PROBABILITY = 0.002;
