
export enum MazeItemKey {
  FRUIT = "FRUIT",
  BRAIN = "BRAIN",
  MULTIPLIER_ITEM = "MULTIPLIER_ITEM"
}


export const FRUIT_SPAWN_BASE_PROBABILITY = 0.004;
export const FRUIT_PICKUP_POINTS_BASE_AMOUNT = 10;
export const FRUIT_PICKUP_POINTS_BASE_AMOUNT_MULTIPLIER = 1.2;

export const BRAIN_SPAWN_BASE_PROBABILITY = 0.001;
export const BRAIN_STARTING_TILE_DISTANCE = 20;

export const MULTIPLIER_ITEM_SPAWN_BASE_PROBABILITY = 0.001;
export const MULTIPLIER_ITEM_BASE_MULTIPLIER = 2;
