import BiomeColorPalette from "models/BiomeColorPalette";


export const DEFAULT_PLAYER_COLOR = '#1EC438';
export const DEFAULT_RNG_BOT_COLOR = '#0f7ebc';
export const DEFAULT_EMPTY_COLOR = 'white';
export const DEFAULT_DEAD_END_COLOR = '#F13241';
export const DEFAULT_MULTIPLIER_ITEM_PLAYER_COLOR = '#E3E95C';
export const DEFAULT_SMART_PATHING_PLAYER_COLOR = '#DBAED8';
export const DEFAULT_VISITED_TILE_COLOR = '#021aee';
export const DEFAULT_MAZE_WALL_COLOR = '#438f19';
export const DEFAULT_UNLIMITED_SPLIT_BOT_PLAYER_COLOR = '#3E9BC7'


export const BIOME_0_COLOR_PALETTE = new BiomeColorPalette(
  DEFAULT_PLAYER_COLOR, 
  DEFAULT_RNG_BOT_COLOR,
  DEFAULT_EMPTY_COLOR,
  DEFAULT_VISITED_TILE_COLOR,
  DEFAULT_MAZE_WALL_COLOR,
  DEFAULT_DEAD_END_COLOR,
  DEFAULT_SMART_PATHING_PLAYER_COLOR,
  DEFAULT_MULTIPLIER_ITEM_PLAYER_COLOR,
  DEFAULT_UNLIMITED_SPLIT_BOT_PLAYER_COLOR
);
export const BIOME_1_COLOR_PALETTE = new BiomeColorPalette(
  DEFAULT_PLAYER_COLOR, 
  DEFAULT_RNG_BOT_COLOR,
  DEFAULT_EMPTY_COLOR,
  DEFAULT_VISITED_TILE_COLOR,
  DEFAULT_MAZE_WALL_COLOR,
  DEFAULT_DEAD_END_COLOR,
  DEFAULT_SMART_PATHING_PLAYER_COLOR,
  DEFAULT_MULTIPLIER_ITEM_PLAYER_COLOR,
  DEFAULT_UNLIMITED_SPLIT_BOT_PLAYER_COLOR
);
