import BiomeColorPalette from "models/BiomeColorPalette";


export const DEFAULT_PLAYER_COLOR = '#1EC438';
export const DEFAULT_RNG_BOT_COLOR = 'black';
export const DEFAULT_EMPTY_COLOR = 'white';
export const DEFAULT_DEAD_END_COLOR = '#F13241';
export const DEFAULT_MULTIPLIER_ITEM_PLAYER_COLOR = '#E3E95C';
export const DEFAULT_SMART_PATHING_PLAYER_COLOR = '#dbaed8';
export const DEFAULT_VISITED_TILE_COLOR = '#7CFCFF';
export const DEFAULT_MAZE_WALL_COLOR = 'black';


export const BIOME_0_COLOR_PALETTE = new BiomeColorPalette(
  DEFAULT_PLAYER_COLOR, 
  DEFAULT_RNG_BOT_COLOR,
  DEFAULT_EMPTY_COLOR,
  DEFAULT_VISITED_TILE_COLOR,
  DEFAULT_MAZE_WALL_COLOR,
  DEFAULT_DEAD_END_COLOR,
  DEFAULT_SMART_PATHING_PLAYER_COLOR,
  DEFAULT_MULTIPLIER_ITEM_PLAYER_COLOR
);
export const BIOME_1_COLOR_PALETTE = new BiomeColorPalette(
  DEFAULT_PLAYER_COLOR, 
  DEFAULT_RNG_BOT_COLOR,
  DEFAULT_EMPTY_COLOR,
  DEFAULT_VISITED_TILE_COLOR,
  DEFAULT_MAZE_WALL_COLOR,
  DEFAULT_DEAD_END_COLOR,
  DEFAULT_SMART_PATHING_PLAYER_COLOR,
  DEFAULT_MULTIPLIER_ITEM_PLAYER_COLOR,
);
