import BiomeColorPalette from "models/BiomeColorPalette";


export const DEFAULT_COLORS = {
  PLAYER_COLOR: '#1EC438',
  RNG_BOT_COLOR: 'black',
  EMPTY_COLOR: 'white',
  VISITED_TILE_COLOR: '#7CFCFF',
  MAZE_WALL_COLOR: '#EEE',
  DEAD_END_COLOR: '#F13241',
  SMART_PATHING_PLAYER_COLOR: '#DBAED8',
  MULTIPLIER_ITEM_PLAYER_COLOR: '#E3E95C',
  UNLIMITED_SPLIT_BOT_PLAYER_COLOR: '#3E9BC7',
}

export const BIOME_0_COLORS = {
  PLAYER_COLOR: '#ffde7d',
  RNG_BOT_COLOR: '#ff5722',
  EMPTY_COLOR: 'white',
  VISITED_TILE_COLOR: '#3fc1c9',
  MAZE_WALL_COLOR: '#f5f5f5',
  DEAD_END_COLOR: '#fc5185',
  SMART_PATHING_PLAYER_COLOR: '#DBAED8',
  MULTIPLIER_ITEM_PLAYER_COLOR: '#E3E95C',
  UNLIMITED_SPLIT_BOT_PLAYER_COLOR: '#3E9BC7',
}

export const BIOME_1_COLORS = {
  PLAYER_COLOR: '#00b8a9',
  RNG_BOT_COLOR: '#2f5d62',
  EMPTY_COLOR: 'white',
  VISITED_TILE_COLOR: '#ffde7d',
  MAZE_WALL_COLOR: '#864000',
  DEAD_END_COLOR: '#fc5185',
  SMART_PATHING_PLAYER_COLOR: '#DBAED8',
  MULTIPLIER_ITEM_PLAYER_COLOR: '#E3E95C',
  UNLIMITED_SPLIT_BOT_PLAYER_COLOR: '#3E9BC7',
}



export const BIOME_0_COLOR_PALETTE = new BiomeColorPalette(
  BIOME_0_COLORS.PLAYER_COLOR,
  BIOME_0_COLORS.RNG_BOT_COLOR,
  BIOME_0_COLORS.EMPTY_COLOR,
  BIOME_0_COLORS.VISITED_TILE_COLOR,
  BIOME_0_COLORS.MAZE_WALL_COLOR,
  BIOME_0_COLORS.DEAD_END_COLOR,
  BIOME_0_COLORS.SMART_PATHING_PLAYER_COLOR,
  BIOME_0_COLORS.MULTIPLIER_ITEM_PLAYER_COLOR,
  BIOME_0_COLORS.UNLIMITED_SPLIT_BOT_PLAYER_COLOR
);
export const BIOME_1_COLOR_PALETTE = new BiomeColorPalette(
  DEFAULT_COLORS.PLAYER_COLOR,
  DEFAULT_COLORS.RNG_BOT_COLOR,
  DEFAULT_COLORS.EMPTY_COLOR,
  DEFAULT_COLORS.VISITED_TILE_COLOR,
  DEFAULT_COLORS.MAZE_WALL_COLOR,
  DEFAULT_COLORS.DEAD_END_COLOR,
  DEFAULT_COLORS.SMART_PATHING_PLAYER_COLOR,
  DEFAULT_COLORS.MULTIPLIER_ITEM_PLAYER_COLOR,
  DEFAULT_COLORS.UNLIMITED_SPLIT_BOT_PLAYER_COLOR
);
