
export enum MazeItemKey {
  FRUIT = "FRUIT",
  BRAIN = "BRAIN",
  MULTIPLIER = "MULTIPLIER",
  BLACK_HOLE = "BLACK_HOLE",
  UNLIMITED_SPLITS = "UNLIMITED_SPLITS",
  GHOST = "GHOST"
}

export const BANANA_IMAGE_URL = 'img/banana2.png'
export const APPLE_IMAGE_URL = 'img/apple.png'
export const ORANGE_IMAGE_URL = 'img/orange.png'
export const GRAPES_IMAGE_URL = 'img/grapes.png'
export const CHERRY_IMAGE_URL = 'img/cherry.png'

export const FRUIT_SPAWN_UPGRADE_FLAT_INCREASE_PROBABILITY = 0.0005;
export const FRUIT_SPAWN_BASE_PROBABILITY = 0.005;

export const FRUIT_PICKUP_POINTS_BASE_AMOUNT_MULTIPLIER = 1.2;

export const BRAIN_SPAWN_BASE_PROBABILITY = 0.001;
export const BRAIN_SPAWN_UPGRADE_FLAT_INCREASE_PROBABILITY = 0.0005;
export const BRAIN_STARTING_TILE_DISTANCE = 20;

export const BLACK_HOLE_ITEM_SPAWN_BASE_PROBABILITY = 0.002;
export const BLACK_HOLE_ITEM_SPAWN_BASE_INCREASE_AMOUNT_PER_BIOME = 0.001;

export const UNLIMITED_SPLITS_PROBABILITY = 0.0015;

export const GHOST_ITEM_SPAWN_PROBABILITY = 0.0015;
export const GHOST_ITEM_STARTING_TILE_DISTANCE = 20;
