import Upgrade from "upgrades/Upgrade";

export enum UpgradeKey {
  // Bot
  AUTO_MOVE = "AUTO_MOVE",
  PRIORITIZE_UNVISITED = "PRIORITIZE_UNVISITED",
  AVOID_REVISIT_LAST_POSITION = "AVOID_REVISIT_LAST_POSITION",
  AUTO_EXIT_MAZE = "AUTO_EXIT_MAZE",
  PLAYER_MOVE_INDEPENDENTLY = "PLAYER_MOVE_INDEPENDENTLY",
  TELEPORT_BOT_BACK_TO_PLAYER = "TELEPORT_BOT_BACK_TO_PLAYER",
  TELEPORT_PLAYER_BACK_TO_BOT = "TELEPORT_PLAYER_BACK_TO_BOT",
  BOT_SPLIT_DIRECTION = "BOT_SPLIT_DIRECTION",
  BOT_SPLIT_BOT_AUTO_MERGE = "BOT_SPLIT_BOT_AUTO_MERGE",
  BOT_MOVEMENT_SPEED = "BOT_MOVEMENT_SPEED",
  BOT_REMEMBER_DEADEND_TILES = "BOT_REMEMBER_DEADEND_TILES",
  BOT_LUCKY_GUESS = "BOT_LUCK",
  // Maze
  MAZE_SIZE_UPGRADE = "MAZE_SIZE_UPGRADE",
  POINTS_PER_VISIT = "POINTS_PER_VISIT",
  POINTS_PER_REVISIT = "POINTS_PER_REVISIT",
  MAZE_COMPLETION_BONUS = "MAZE_COMPLETION_BONUS",
  // Items
  FRUIT_SPAWN = "FRUIT_SPAWN",
  BRAIN_SPAWN = "BRAIN_SPAWN",
  BRAIN_TILE_DISTANCE = "BRAIN_TILE_DISTANCE",
  FRUIT_PICKUP_POINTS = "FRUIT_PICKUP_POINTS",
  // Power Ups
  SPEED_UP_ACTIVATE_DURATION = "SPEED_UP_ACTIVATE_DURATION",
  SPEED_UP_MULTIPLIER_STRENGTH = "SPEED_UP_MULTIPLIER_STRENGTH",
  MULTIPLIER_POWER_UP_ACTIVATE_DURATION = "MULTIPLIER_POWER_UP_ACTIVATE_DURATION",
  MULTIPLIER_POWER_UP_STRENGTH = "MULTIPLIER_POWER_UP_STRENGTH",
  // "Feature" Upgrades
  DESTRUCTIBLE_WALLS = "DESTRUCTIBLE_WALLS",
  // Biomes
  BIOME = "BIOME"
}

export enum UpgradeType {
  BOT = "BOT",
  MAZE = "MAZE",
  MOVEMENT = "MOVEMENT",
  ITEM = "ITEM",
  OTHER = "OTHER",
  POWER_UP = "POWER_UP",
}

// Bot
export const BOT_AUTO_MOVE_UPGRADE_COST = 100;

export const PRIORITIZE_UNVISITED_UPGRADE_COST = 300;
export const AVOID_REVISIT_LAST_POSITION_UPGRADE_COST = 500;
export const ALLOW_PLAYER_TO_MOVE_INDEPENDENTLY_UPGRADE_COST = 500;

export const AUTO_EXIT_MAZE_UPGRADE_BASE_COST = 250;
export const AUTO_EXIT_MAZE_UPGRADE_BASE_COST_MULTIPLIER = 2;

export const TELEPORT_PLAYER_BACK_TO_BOT_UPGRADE_COST = 750;
export const TELEPORT_BOT_BACK_TO_PLAYER_UPGRADE_COST = 750;

export const SPLIT_DIRECTION_UPGRADE_BASE_COST = 5000;
export const SPLIT_DIRECTION_UPGRADE_BASE_MULTIPLIER = 3;

export const SPLIT_BOT_AUTO_MERGE_UPGRADE_COST = 50000;

export const BOT_MOVEMENT_UPGRADE_BASE_COST = 10;
export const BOT_MOVEMENT_UPGRADE_BASE_COST_MUTLIPLIER = 1.1;

export const BOT_REMEMBER_DEADEND_TILES_UPGRADE_BASE_COST = 1000;
export const BOT_REMEMBER_DEADEND_TILES_UPGRADE_BASE_COST_MULTIPLIER = 3;

export const BOT_LUCKY_GUESS_UPGRADE_BASE_COST = 5000;
export const BOT_LUCKY_GUESS_UPGRADE_BASE_COST_MULTIPLIER = 2;
export const BOT_LUCKY_GUESS_UPGRADE_INCREASE_AMOUNT = 0.01;

// Maze
export const MAZE_COMPLETION_BONUS_BASE_MULTIPLIER = 0.75;
export const MAZE_COMPLETION_BONUS_UPGRADE_SIZE_MULTIPLIER = 1.1;
export const MAZE_COMPLETION_BONUS_UPGRADE_BASE_COST = 100;
export const MAZE_COMPLETION_BONUS_UPGRADE_BASE_COST_MULTIPLIER = 1.2;

export const MAZE_SIZE_UPGRADE_BASE_COST = 300;
export const MAZE_SIZE_UPGRADE_BASE_COST_MULTIPLIER = 1.8;

export const POINTS_PER_VISIT_UPGRADE_BASE_COST = 10;
export const POINTS_PER_VISIT_UPGRADE_BASE_COST_MULTIPLIER = 1.3;
export const POINTS_PER_VISIT_BASE_AMOUNT_MULTIPLIER = 1.05;

export const POINTS_PER_REVISIT_UPGRADE_BASE_COST = 1000;
export const POINTS_PER_REVISIT_UPGRADE_BASE_COST_MULTIPLIER = 1.14;
export const TILE_REVISIT_BASE_MULTIPLIER = 0;
export const TILE_REVISIT_BASE_MULTIPLIER_INCREASE_PERCENT = 0.0075;

export const DESTRUCTIBLE_WALL_BASE_SPAWN_RATE = 0.001;
export const DESTRUCTIBLE_WALL_BASE_SPAWN_RATE_INCREASE_PER_BIOME = 0.001;

// Items
export const FRUIT_SPAWN_UPGRADE_BASE_COST = 100;
export const FRUIT_SPAWN_UPGRADE_BASE_COST_MULTIPLIER = 1.35;
export const FRUIT_PICKUP_POINTS_UPGRADE_BASE_COST = 100;
export const FRUIT_PICKUP_POINTS_UPGRADE_BASE_COST_MULTIPLIER = 1.35;

export const BRAIN_SPAWN_RATE_UPGRADE_BASE_COST = 100;
export const BRAIN_SPAWN_RATE_UPGRADE_BASE_COST_MULTIPLIER = 2;

export const BRAIN_TILE_DISTANCE_UPGRADE_BASE_COST = 10000;
export const BRAIN_TILE_DISTANCE_UPGRADE_BASE_COST_MULTIPLIER = 1.5;
export const BRAIN_TILE_DISTANCE_UPGRADE_INCREASE_AMOUNT = 5;

// Power Ups
export const MULTIPLIER_POWER_UP_STRENGTH_BASE_COST = 40000;
export const MULTIPLIER_POWER_UP_STRENGTH_BASE_COST_MULTIPLIER = 1.5;

export const MULTIPLIER_POWER_UP_SPAWN_RATE_BASE_COST = 20000;
export const MULTIPLIER_POWER_UP_SPAWN_RATE_COST_MULTIPLIER = 1.5;

export const SPEED_UP_POWER_UP_ACTIVATE_DURATION_BASE_COST = 10000;
export const SPEED_UP_POWER_UP_ACTIVATE_DURATION_COST_MULTIPLIER = 1.5;

export const SPEED_UP_MULTIPLIER_STRENGTH_BASE_COST = 10000;
export const SPEED_UP_MULTIPLIER_STRENGTH_COST_MULTIPLIER = 1.5;

export const BIOME_UPGRADE_COST_ARR = [
  200,
  400,
  1000,
  2000,
  4000,
  8000,
  15000,
  25000,
  40000,
  70000,
  120000,
  240000
]

export const BIOME_UPGRADE_BASE_MULTPLIER = 1.5;

export const UPGRADE_TYPE_TO_UI_KEY_MAP = new Map<UpgradeType, string>([
  [UpgradeType.BOT, "botUpgradeHeader"],
  [UpgradeType.ITEM, "itemUpgradeHeader"],
  [UpgradeType.MAZE, "mazeUpgradeHeader"],
  [UpgradeType.MOVEMENT, "movementUpgradeHeader"],
  [UpgradeType.POWER_UP, "powerUpUpgradeHeader"],
  [UpgradeType.OTHER, null],
]);
